// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026/3/1 19:49:58
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["E:/AAA1/CampusHub-website/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/AAA1/CampusHub-website/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/AAA1/CampusHub-website/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/AAA1/CampusHub-website/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/AAA1/CampusHub-website/app/plugins/**/*.{js,ts,mjs}","E:/AAA1/CampusHub-website/app/composables/**/*.{js,ts,mjs}","E:/AAA1/CampusHub-website/app/utils/**/*.{js,ts,mjs}","E:/AAA1/CampusHub-website/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","E:/AAA1/CampusHub-website/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","E:/AAA1/CampusHub-website/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;